apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackertime-deployment
  labels:
    app: hackertime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackertime
  template:
    metadata:
      labels:
        app: hackertime
    spec:
      containers:
        - name: hackertime
          image: registry.opensuse.org/opensuse/tumbleweed
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /
              name: host-volume
      volumes:
        - name: host-volume
          hostPath:
            type: DirectoryOrCreate
            path: $(HACKERTIME_VOLUME_PATH)
