apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackertime-deployment
  labels:
    app: hackertime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackertime
  template:
    metadata:
      labels:
        app: hackertime
    spec:
      containers:
        - name: hackertime
          image: registry.opensuse.org/opensuse/tumbleweed
          volumeMounts:
            - mountPath: /
              readOnly: false
              name: host-volume
      volumes:
        - name: host-volume            
          hostPath:
            type: DirectoryOrCreate
            path: /$(HACKERTIME_VOLUME_PATH)
