apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackertime-deployment
  labels:
    app: hackertime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackertime
  template:
    metadata:
      labels:
        app: hackertime
    spec:
      containers:
        - name: hackertime
          image: registry.opensuse.org/opensuse/tumbleweed
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
          volumeMounts:
            - name: host-volume
              mountPath: "/"
          env:
            - name: HOST_USER_ID
              value: "1000"
            - name: HOST_GROUP_ID
              value: "1000"
      volumes:
        - name: host-volume
          hostPath:
            path: $(HACKERTIME_VOLUME_PATH)
            type: Directory
          secret:
            secretName: host-path
            items:
              - key: path
                path: variables.env
      dnsPolicy: Default
      restartPolicy: Always
